import React, { Suspense } from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';
import LazyVisible from '@site/src/components/docs/legend/LazyVisible';

const componentMap = {
  LegendItemWithProcessing: React.lazy(() => import('@site/src/components/docs/LegendItemWithProcessing.jsx')),
  LegendItem: React.lazy(() => import('@site/src/components/docs/LegendItem.js')),
  LegendItemAutogeneratedTraffic: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedTraffic.js')),
  LegendItemAutogeneratedEmergency: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedEmergency.js')),
  LegendItemAutogeneratedHealth: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedHealth.js')),
  LegendItemAutogeneratedTourism: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedTourism.js')),
  LegendItemAutogeneratedEntertainment: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedEntertainment.js')),
  LegendItemAutogeneratedAccomodation: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedAccomodation.js')),
  LegendItemAutogeneratedEducation: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedEducation.js')),
  LegendItemAutogeneratedSustenance: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedSustenance.js')),
  LegendItemAutogeneratedNatural: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedNatural.js')),
  LegendItemAutogeneratedSport: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedSport.js')),
  LegendItemAutogeneratedFinance: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedFinance.js')),
  LegendItemAutogeneratedAdministrative: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedAdministrative.js')),
  LegendItemAutogeneratedService: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedService.js')),
  LegendItemAutogeneratedShop: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedShop.js')),
  LegendItemAutogeneratedOffice: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedOffice.js')),
  LegendItemAutogeneratedCraft: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedCraft.js')),
  LegendItemAutogeneratedClub: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedClub.js')),
  LegendItemAutogeneratedBarrier: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedBarrier.js')),
  LegendItemAutogeneratedManmade: React.lazy(() => import('@site/src/components/docs/autogenerated/LegendItemAutogeneratedManmade.js')),
};

export default function LazyLegendContent({ sectionData }) {
  if (!sectionData || !sectionData.component) {
    return null;
  }

  const { component, height } = sectionData;

  const LegendComponent = componentMap[component];

  if (!LegendComponent) {
    return <div style={{color: 'red'}}>Error: Component '{component}' not found in componentMap.</div>;
  }

  const getProps = () => {
    switch (component) {
      case 'LegendItemWithProcessing':
        return { svgPath: sectionData.svgPath, svgParts: sectionData.svgParts };
      case 'LegendItem':
        return { itemsMap: sectionData.itemsMap };
      default:
        return {};
    }
  };

  return (
    <div style={{
      minHeight: height ? `${height}px` : '240px',
      // A subtle background can indicate that content is coming.
      backgroundColor: height ? '#fafafa' : 'transparent',
    }}>
      <LazyVisible>
        <BrowserOnly>
          {() => (
            <Suspense fallback={
              <div style={{ width: '100%', height: '100%', display: 'grid', placeContent: 'center', color: '#999' }}>
                Loading…
              </div>
            }>
              <LegendComponent {...getProps()} />
            </Suspense>
          )}
        </BrowserOnly>
      </LazyVisible>
    </div>
  );
}